### ISSUE TITLE
People's reply text don't show their name shows their ID

### ISSUE THREAD

**Issue by aniseeo** [syphon-org/syphon#288]
![Screenshot_2021-07-08-11-59-54-34](https://user-images.githubusercontent.com/41234183/124870190-1c950d80-dfe4-11eb-84b4-948e97b3c8f4.jpg)

Thanks for fixing the previous bug. When replying someone text in the text box their id is shown not their name also doesn't show reply text in the box. so it's deficult to understand someone replying text to someone.

**Comment by aniseeo** [comment]
![Screenshot_2021-07-08-12-30-22-70](https://user-images.githubusercontent.com/41234183/124873453-4fd99b80-dfe8-11eb-8ff0-a864fb51a8e9.jpg)


I mean like this way to identify.

Thanks

**Comment by aniseeo** [comment]
![Screenshot_2021-07-08-12-51-35-18](https://user-images.githubusercontent.com/41234183/124875977-53baed00-dfeb-11eb-98d1-f06c484fec02.jpg)


See. I think it's not look's good.

**Comment by 0x1a8510f2** [comment]
The reason for this is that currently Syphon does not support rich replies (where the client knows that the message is a reply) or HTML (used by the sending client to style the reply as a fallback for rich replies. That's why it relies on unstyled text which does sometimes look confusing. This isn't a big though, or a design choice, just something yet to be implemented.

**Comment by simplepad** [comment]
@ereio This have been fixed, isn't it? Rich replies work for me in both directions.

**Comment by AnisTaluqdar** [comment]
Still present in version v1.2.7

**Comment by AnisTaluqdar** [comment]
Still present in version v0.2.8

How do you make it rich replies? Can you give some screenshot?

**Comment by notramo** [comment]
A Matrix spec change is being actively worked on (expect merging in a few weeks), so I guess until it's ready, this feature won't get much attention.
https://github.com/matrix-org/matrix-doc/pull/2781
https://github.com/matrix-org/matrix-doc/pull/3676
